In [ ]:
Exercise 1:
Create a NumPy array `arr` of shape (4, 4) with values ranging from 0 to 15. Access and print the element at row 2, column 3.

In [1]:
import numpy as np

arr = np.arange(16).reshape(4, 4)
print(arr[2, 3])

11


In [ ]:
Exercise 2:
Create a NumPy array `arr` of shape (5, 5) with random integer values between 0 and 9. Access and print the elements in the second column.

In [2]:
import numpy as np

arr = np.random.randint(0, 10, size=(5, 5))
print(arr[:, 1])

[0 6 0 7 0]


In [ ]:
Exercise 3:
Create a NumPy array `arr` of shape (6, 6) with random integer values between 10 and 50. Access and print the elements in the first two rows and last three columns.

In [4]:
import numpy as np

arr = np.random.randint(10, 51, size=(6, 6))
# print(arr[:2, -3:])
arr

array([[16, 49, 13, 38, 14, 35],
       [15, 43, 31, 47, 24, 42],
       [32, 16, 37, 50, 50, 17],
       [37, 17, 27, 34, 32, 45],
       [26, 27, 49, 32, 40, 25],
       [29, 35, 45, 12, 47, 38]])

In [5]:
print(arr[:2, -3:])

[[38 14 35]
 [47 24 42]]


In [ ]:
Exercise 4:
Create a NumPy array `arr` of shape (3, 3, 3) with consecutive numbers from 1 to 27. Access and print the element at index (2, 1, 0).

In [ ]:
import numpy as np

arr = np.arange(1, 28).reshape(3, 3, 3)
print(arr[2, 1, 0])

In [ ]:
Exercise 5:
Create a NumPy array `arr` of shape (4, 4) with consecutive numbers from 1 to 16. Access and print all the elements in the last row.

In [ ]:
import numpy as np

arr = np.arange(1, 17).reshape(4, 4)
print(arr[-1, :])

In [ ]:
Exercise 6:
Create a NumPy array `arr` of shape (5, 5) with random float values between 0 and 1. Access and print the elements in the diagonal.

In [ ]:
import numpy as np

arr = np.random.random((5, 5))
print(np.diag(arr))

In [ ]:
Exercise 7:
Create a NumPy array `arr` of shape (6, 6) with random integer values between 0 and 9. Access and print the elements in the first and last column.

In [ ]:
import numpy as np

arr = np.random.randint(0, 10, size=(6, 6))
print(arr[:, [0, -1]])


In [ ]:
Exercise 8:
Create a NumPy array `arr` of shape (3, 4) with consecutive numbers from 1 to 12. Access and print the elements in the first two rows and columns.

In [ ]:
import numpy as np

arr = np.arange(1, 13).reshape(3, 4)
print(arr[:2, :2])

In [ ]:
Exercise 9:
Create a NumPy array `arr` of shape (4, 4) with random integer values between 1 and 10. Access and print the elements greater than 5.

In [ ]:
import numpy as np

arr = np.random.randint(1, 11, size=(4, 4))
print(arr[arr > 5])

In [ ]:
Exercise 10:
Create a NumPy array `arr` of shape (6, 6) with random integer values between 1 and 100. Access and print

 the elements in the first three rows, last three columns, and skipping every second element.


In [4]:
import numpy as np

arr = np.random.randint(1, 101, size=(6, 6))
arr

array([[ 44,  18,  48,  67,  37,  64],
       [ 27,  29,  25,   9,  78,  16],
       [ 72,  59,  59,  83,  75,   4],
       [ 41,  94,   9,  15, 100,  48],
       [ 48,  11,  49,  32,  42,   4],
       [ 61,   1,  87,  97,  64,   7]])

In [5]:
arr[0:3,-3::2]

array([[67, 64],
       [ 9, 16],
       [83,  4]])