Exercise 1:

Question: Write a NumPy code to create a 3x3 matrix with values ranging from 1 to 9 and print the matrix.

In [1]:
import numpy as np

matrix = np.arange(1, 10).reshape(3, 3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
Exercise 2:

Question: Create a NumPy array with values from 0 to 9, and then reshape it to a 3x3 matrix. Print the reshaped matrix.

In [4]:

import numpy as np

arr = np.arange(0,9)
matrix = arr.reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
Exercise 3:

Question: Create a 5x5 identity matrix using NumPy and print it.

In [3]:
import numpy as np

matrix = np.eye(5)
print(matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
Exercise 4:

Question: Create a 2D NumPy array with random values between 0 and 1. Print the array.

In [4]:
import numpy as np

array = np.random.random((3, 4))
print(array)

[[0.66195487 0.64590568 0.8605902  0.1617966 ]
 [0.25283164 0.410901   0.75520206 0.86513201]
 [0.54834566 0.57659543 0.03884449 0.22195107]]


In [ ]:
Exercise 5:

Question: Create a NumPy array with values ranging from 1 to 20. Print the elements at even indices.

In [5]:
import numpy as np

array = np.arange(1, 21)
even_indices = array[::2]
print(even_indices)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
Exercise 6:

Question: Create a 4x4 matrix with random values between 1 and 10. Find the maximum and minimum values in the matrix.

In [6]:
import numpy as np

matrix = np.random.randint(1, 10, (4, 4))
maximum = np.max(matrix)
minimum = np.min(matrix)

print("Maximum:", maximum)
print("Minimum:", minimum)

Maximum: 9
Minimum: 1


In [ ]:
Exercise 7:

Question: Create a NumPy array with values ranging from 0 to 9. Reverse the order of the elements and print the reversed array.

In [7]:
import numpy as np

array = np.arange(10)
reversed_array = np.flip(array)
print(reversed_array)

[9 8 7 6 5 4 3 2 1 0]


In [ ]:
Exercise 8:

Question: Create a 3x3 matrix with random integers between 1 and 100. Calculate the sum of all the elements in the matrix.

In [ ]:
import numpy as np

matrix = np.random.randint(1, 100, (3, 3))
sum_of_elements = np.sum(matrix)
print("Sum of elements:", sum_of_elements)

In [ ]:
Exercise 9:

Question: Create a NumPy array with 10 equally spaced values between 0 and 1. Print the array.

In [8]:
import numpy as np

array = np.linspace(0, 1, 10)
print(array)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
Exercise 10:

Question: Create a 2x3 matrix with random integers between 1 and 10. Reshape the matrix to a 3x2 matrix and print the reshaped matrix.

In [ ]:
import numpy as np

matrix = np.random.randint(1, 10, (2, 3))
reshaped_matrix = matrix.reshape(3, 2)
print(reshaped_matrix)

In [ ]:
Exercise 11:

Question: Create a 4x4 matrix with random integers between 1 and 100. Calculate the mean of each row and print the resulting array.

In [9]:
import numpy as np

matrix = np.random.randint(1, 100, (4, 4))
row_means = np.mean(matrix, axis=1)
print(row_means)

[55.25 46.   34.75 18.5 ]


In [ ]:
Exercise 12:

Question: Create a NumPy array with values ranging from 0

 to 9. Replace all odd numbers in the array with -1 and print the modified array.

In [ ]:
import numpy as np

array = np.arange(10)
array[array % 2 != 0] = -1
print(array)


In [ ]:
Exercise 13:

Question: Create a 3x3 matrix with random integers between 1 and 10. Multiply the matrix by a scalar value of 2 and print the result.

In [ ]:
import numpy as np

matrix = np.random.randint(1, 10, (3, 3))
result = matrix * 2
print(result)

In [ ]:
Exercise 14:

Question: Create a NumPy array with values ranging from 1 to 10. Square each element in the array and print the resulting array.

In [ ]:
import numpy as np

array = np.arange(1, 11)
squared_array = np.square(array)
print(squared_array)

In [ ]:
Exercise 15:

Question: Create a 3x3 matrix with random integers between 1 and 10. Find the sum of each column and print the resulting array.


In [ ]:
import numpy as np

matrix = np.random.randint(1, 10, (3, 3))
column_sums = np.sum(matrix, axis=0)
print(column_sums)

In [ ]:
Exercise 16:

Question: Create a 5x5 matrix with random integers between 1 and 100. Find the indices of the maximum and minimum values in the matrix.


In [10]:
import numpy as np

matrix = np.random.randint(1, 100, (5, 5))
max_index = np.unravel_index(np.argmax(matrix), matrix.shape)
min_index = np.unravel_index(np.argmin(matrix), matrix.shape)

print("Maximum value index:", max_index)
print("Minimum value index:", min_index)

Maximum value index: (0, 0)
Minimum value index: (0, 4)


In [ ]:
Exercise 17:

Question: Create a NumPy array with values ranging from 0 to 9. Extract all the odd numbers from the array and print them.


In [ ]:
import numpy as np

array = np.arange(10)
odd_numbers = array[array % 2 != 0]
print(odd_numbers)

In [ ]:
Exercise 18:

Question: Create a 2x2 matrix with random integers between 1 and 10. Calculate the determinant of the matrix and print the result.


In [12]:
import numpy as np

matrix = np.random.randint(1, 10, (2, 2))
print(matrix)
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

[[9 7]
 [7 6]]
Determinant: 5.000000000000001


In [ ]:
Exercise 19:

Question: Create two NumPy arrays with values ranging from 1 to 5. Concatenate the arrays vertically and print the resulting array.


In [ ]:
import numpy as np

array1 = np.arange(1, 6)
array2 = np.arange(1, 6)
concatenated_array = np.vstack((array1, array2))
print(concatenated_array)

In [ ]:
Exercise 20:

Question: Create a 3x3 matrix with random integers between 1 and 10. Calculate the square root of each element in the matrix and print the resulting matrix.


In [13]:
import numpy as np

matrix = np.random.randint(1, 10, (3, 3))
sqrt_matrix = np.sqrt(matrix)
print(sqrt_matrix)

[[1.73205081 1.         2.82842712]
 [1.73205081 2.         3.        ]
 [1.         1.41421356 2.        ]]
